import Head from "next/head";

import { getLayout } from "@/components/layouts/MainLayout";

import { api } from "@/utils/api";

export const HomePage = () => {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>{hello.data ? hello.data.greeting : "Loading tRPC query..."}</p>
    </>
  );
};

HomePage.getLayout = getLayout;

export default HomePage;
